### ISSUE TITLE
Rclone v1.55 release

### ISSUE THREAD

**Issue by ncw** [rclone/rclone#5162]
As an experiment I'm creating a release issue.

The release is planned for 31st March 20201 (that is the date in the milestone). That is just over a week away so I'd like not to merge features which might break too much stuff from now on.

I've been merging my backlog in an attempt to hit that date. I have two small features to merge - a configuration for the backend cache and a JSON config string for the rc.

Is there anything that you @rclone/rclone developers would like to see in the release too? Bear in mind that there will be another release along soon in 6-8 weeks!

- [x] Issue template needs merging: #5096
- [x] This fix needs merging #5143
- [x] And so does this one #5139

**Comment by darthShadow** [comment]
I would really like to have ideally a PPA or at least a separate APT (and yum) repo set up before the release. This will allow us to move away from the upstream limitation in the various OS repositories.

Linked issue: https://github.com/rclone/rclone/issues/5070

**Comment by ncw** [comment]
If you can get it done before the release deadline then :+1: from me :-)
